# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: 'Build'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/DaylioData/DaylioData.sln

    - name: Build
      run: dotnet build src/DaylioData/DaylioData.sln --configuration Release

    - name: Test
      run: dotnet test src/DaylioData/DaylioData.sln --no-build --verbosity normal

    - name: 'Archive Files'
      run: tar -cvf BuildResults.tar BuildResults/

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: Build-Artifacts
        path: BuildResults.tar
        retention-days: 60
