# This workflow will publish a nuget package
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

  release:

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --no-build --configuration Release --output BuildResults

    - name: Set API Key
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      run: nuget setapikey $NUGET_AUTH_TOKEN -Source "https://api.nuget.org/v3/index.json"

    - name: Push
      run: dotnet nuget push ./BuildResults/*.nupkg
